"""Added instructions

Revision ID: 08418cb3e08b
Revises: 12d1737b49e9
Create Date: 2019-11-26 14:57:24.854738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08418cb3e08b'
down_revision = '12d1737b49e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructions',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('scenario_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('source_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('source_parameter', sa.String(length=64), nullable=True),
    sa.Column('target_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_parameter', sa.String(length=64), nullable=False),
    sa.Column('setpoint_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_uuid'], ['scenarios.uuid'], ),
    sa.ForeignKeyConstraint(['setpoint_uuid'], ['setpoints.uuid'], ),
    sa.ForeignKeyConstraint(['source_uuid'], ['devices.uuid'], ),
    sa.ForeignKeyConstraint(['target_uuid'], ['devices.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'conditions', ['uuid'])
    op.create_unique_constraint(None, 'setpoints', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setpoints', type_='unique')
    op.drop_constraint(None, 'conditions', type_='unique')
    op.drop_table('instructions')
    # ### end Alembic commands ###
