"""reformat instructions

Revision ID: 0abf2310d649
Revises: f7a0ccb9057c
Create Date: 2019-09-11 18:49:03.668547

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0abf2310d649'
down_revision = 'f7a0ccb9057c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_instructions', sa.Column('instruction_type_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('scenario_instructions', sa.Column('parameters', sa.String(length=256), nullable=True))
    op.drop_constraint('scenario_instructions_instruction_uuid_fkey', 'scenario_instructions', type_='foreignkey')
    op.create_foreign_key(None, 'scenario_instructions', 'instruction_types', ['instruction_type_uuid'], ['uuid'])
    op.drop_column('scenario_instructions', 'instruction_uuid')
    op.drop_table('instructions')
    op.create_unique_constraint(None, 'triggers', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'triggers', type_='unique')
    op.add_column('scenario_instructions', sa.Column('instruction_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scenario_instructions', type_='foreignkey')
    op.create_foreign_key('scenario_instructions_instruction_uuid_fkey', 'scenario_instructions', 'instructions', ['instruction_uuid'], ['uuid'])
    op.drop_column('scenario_instructions', 'parameters')
    op.drop_column('scenario_instructions', 'instruction_type_uuid')
    op.create_table('instructions',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('type_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_uuid'], ['instruction_types.uuid'], name='instructions_type_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='instructions_pkey'),
    sa.UniqueConstraint('uuid', name='instructions_uuid_key')
    )
    # ### end Alembic commands ###
