"""Add rooms

Revision ID: 0be4d9a4469a
Revises: 531f36e731cf
Create Date: 2019-11-19 13:59:18.309129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0be4d9a4469a'
down_revision = '531f36e731cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('device_room_binds',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('device_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('room_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.uuid'], ),
    sa.ForeignKeyConstraint(['room_uuid'], ['endpoints.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'device_parameter_bindings', ['uuid'])
    op.create_unique_constraint(None, 'devices', ['uuid'])
    op.create_unique_constraint(None, 'driver_instances', ['uuid'])
    op.create_unique_constraint(None, 'driver_parameters', ['uuid'])
    op.create_unique_constraint(None, 'endpoints', ['uuid'])
    op.create_unique_constraint(None, 'interface_bindings', ['uuid'])
    op.create_unique_constraint(None, 'interface_params', ['uuid'])
    op.create_unique_constraint(None, 'mqtt_params', ['uuid'])
    op.create_unique_constraint(None, 'mqtt_types', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mqtt_types', type_='unique')
    op.drop_constraint(None, 'mqtt_params', type_='unique')
    op.drop_constraint(None, 'interface_params', type_='unique')
    op.drop_constraint(None, 'interface_bindings', type_='unique')
    op.drop_constraint(None, 'endpoints', type_='unique')
    op.drop_constraint(None, 'driver_parameters', type_='unique')
    op.drop_constraint(None, 'driver_instances', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'device_parameter_bindings', type_='unique')
    op.drop_table('device_room_binds')
    op.drop_table('rooms')
    # ### end Alembic commands ###
