"""Added conditions and setpoints

Revision ID: 12d1737b49e9
Revises: dd0acf882385
Create Date: 2019-11-26 13:41:35.771547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12d1737b49e9'
down_revision = 'dd0acf882385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setpoints',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('conditions',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=False),
    sa.Column('scenario_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('condition_type', sa.Enum('IsEqual', 'IsMore', 'IsLess', 'NotEqual', 'InMode', 'NotInMode', name='conditiontypeenum'), nullable=True),
    sa.Column('target_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('target_parameter_name', sa.String(length=64), nullable=False),
    sa.Column('setpoint_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_uuid'], ['scenarios.uuid'], ),
    sa.ForeignKeyConstraint(['setpoint_uuid'], ['setpoints.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions')
    op.drop_table('setpoints')
    # ### end Alembic commands ###
