"""make endpoints

Revision ID: 1af8addfa34e
Revises: 226c10124b82
Create Date: 2019-09-11 15:37:51.553896

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1af8addfa34e'
down_revision = '226c10124b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_endpoints',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('retain', sa.Boolean(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('mqtt_patterns',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('regex', sa.String(length=256), nullable=False),
    sa.Column('typing', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mqtt_patterns')
    op.drop_table('mqtt_endpoints')
    # ### end Alembic commands ###
