"""adding parameters for driver instances

Revision ID: 226c10124b82
Revises: 863938515119
Create Date: 2019-09-02 16:49:04.502631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226c10124b82'
down_revision = '863938515119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_instances', sa.Column('parameters', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'driver_instances', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_instances', type_='unique')
    op.drop_column('driver_instances', 'parameters')
    # ### end Alembic commands ###
