"""endpoints constraints

Revision ID: 5e2f64b9d13a
Revises: 1af8addfa34e
Create Date: 2019-09-11 15:51:11.516941

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e2f64b9d13a'
down_revision = '1af8addfa34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_endpoints', sa.Column('type_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'mqtt_endpoints', ['uuid'])
    op.create_foreign_key(None, 'mqtt_endpoints', 'mqtt_patterns', ['type_uuid'], ['uuid'])
    op.drop_column('mqtt_endpoints', 'type_id')
    op.create_unique_constraint(None, 'mqtt_patterns', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mqtt_patterns', type_='unique')
    op.add_column('mqtt_endpoints', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mqtt_endpoints', type_='foreignkey')
    op.drop_constraint(None, 'mqtt_endpoints', type_='unique')
    op.drop_column('mqtt_endpoints', 'type_uuid')
    # ### end Alembic commands ###
