"""Added alarm system

Revision ID: 5fea82ea2541
Revises: 3c4e31434950
Create Date: 2019-11-27 16:23:56.362178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fea82ea2541'
down_revision = '3c4e31434950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_params',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'ERROR', 'WARNING', 'INFO', name='alarmseverityenum'), nullable=True),
    sa.Column('ep_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['ep_uuid'], ['endpoints.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm_params')
    # ### end Alembic commands ###
