"""initial migration

Revision ID: 863938515119
Revises: 4759f36b18d4
Create Date: 2019-09-02 16:44:07.111119

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '863938515119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_instances',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('driver', sa.Enum('mqtt', 'virtual', name='driver_enum'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_instances')
    # ### end Alembic commands ###
