"""Fix driver types

Revision ID: ea8722305913
Revises: 5fea82ea2541
Create Date: 2019-11-27 16:28:42.990414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8722305913'
down_revision = '5fea82ea2541'
branch_labels = None
depends_on = None

name = 'drivertypeenum'
tmp_name = 'tmp_' + name

old = ('mqtt', 'iface')
new = sorted(old + ('alarm',))

old_type = sa.Enum(*old, name=name)
new_type = sa.Enum(*new, name=name)

tcr1 = sa.sql.table('driver_instances', sa.Column('driver_type', new_type, nullable=False))
tcr2 = sa.sql.table('endpoints', sa.Column('driver_type', new_type, nullable=False))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alarm_params', ['uuid'])

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)
    new_type.create(op.get_bind())
    op.execute('ALTER TABLE driver_instances ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('ALTER TABLE endpoints ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alarm_params', type_='unique')

    op.execute(tcr1.update().where(tcr1.c.status == 'output_limit_exceeded')
               .values(status='timed_out'))
    op.execute(tcr2.update().where(tcr2.c.status == 'output_limit_exceeded')
               .values(status='timed_out'))

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    old_type.create(op.get_bind())
    op.execute('ALTER TABLE driver_instances ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('ALTER TABLE endpoints ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
    # ### end Alembic commands ###
