"""Restored missing trigger type

Revision ID: ee36b03b1adf
Revises: b2aec60d1af7
Create Date: 2019-11-19 14:14:13.125666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee36b03b1adf'
down_revision = 'b2aec60d1af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trigger_params', ['uuid'])
    triggertypeenum = sa.Enum('ValueChange', 'Manual', name='triggertypeenum')
    triggertypeenum.create(op.get_bind())
    op.add_column('triggers', sa.Column('trigger_type', sa.Enum('ValueChange', 'Manual', name='triggertypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggers', 'trigger_type')
    op.drop_constraint(None, 'trigger_params', type_='unique')
    triggertypeenum = sa.Enum('ValueChange', 'Manual', name='triggertypeenum')
    triggertypeenum.drop(op.get_bind())
    # ### end Alembic commands ###
