"""add mqtt endpoint info

Revision ID: f0f0a3c02af8
Revises: 5e2f64b9d13a
Create Date: 2019-09-11 15:53:09.843561

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0f0a3c02af8'
down_revision = '5e2f64b9d13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_endpoints', sa.Column('connection_on_string', sa.String(length=128), nullable=True))
    op.add_column('mqtt_endpoints', sa.Column('connection_string', sa.String(length=128), nullable=False))
    op.add_column('mqtt_endpoints', sa.Column('name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mqtt_endpoints', 'name')
    op.drop_column('mqtt_endpoints', 'connection_string')
    op.drop_column('mqtt_endpoints', 'connection_on_string')
    # ### end Alembic commands ###
